### ISSUE TITLE
"You are using an outdated version of Auto Disconnect."

### ISSUE THREAD

**Issue by Khikki** [I-No-oNe/Auto-Disconnect#1]
Hi I-No-oNe, I’m having issue launching the client because of the following error: 'You are using an outdated version of Auto Disconnect. Please download the latest version from Morinth.' However, I've already downloaded the latest version from both Morinth and GitHub, but the issue persists.

[latest.log](https://github.com/user-attachments/files/17209783/latest.log)

![image](https://github.com/user-attachments/assets/aa920c7a-d905-4556-8678-8cddba9c73e2)

**Comment by I-No-oNe** [comment]
Hello!
When you launched the game, did you have an internet connection?

**Comment by I-No-oNe** [comment]
@Khikki ?

**Comment by I-No-oNe** [comment]
Because I didn't get any response, I'm closing this issue.

**Comment by thebuildcraft** [comment]
I have the same issue. And yes, I have a working internet connection while launching the game.

**Comment by I-No-oNe** [comment]
> I have the same issue. And yes, I have a working internet connection while launching the game.

Can u provide me logs/other files that show data about the game?

I don't know why, but for some people, it's working, and for some, it's not (I'm suspecting it's maybe a SSL server error)

**Comment by thebuildcraft** [comment]
Ok, I just added the mod and started the game. Here are the logs from starting it: https://mclo.gs/jvMaf5b
I would suggest you make the Update-Watcher less invasive and let the user play anyway.

**Comment by NotMuole** [comment]
Got the same error screen. Any solutions?
